- name: Ajustar swappiness
  hosts: localhost
  become: true
  user: root
  tasks:
    - name: Definir vm.swappiness para 10
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
        reload: yes
